### PR TITLE
gasUsed and gasPrice in a Transaction + tx reference in LiquidityPositionSnapshot

### PR DESCRIPTION
**Pull request by benesjan**
Modifications which allow for easy accounting of tx costs. I needed this functionality in [my project](croco.finance). My deployment of the modified subgraph is [here](https://thegraph.com/explorer/subgraph/benesjan/sushi-swap?selected=logs).

### CODE REVIEW

**Comment by jiro-ono** [comment]
@benesjan Would love to add this to the subgraph, but the problem is we don't have the access token for this forked version due to @zippoxer setting it up originally. I've been in contact with him, and if we can get the access token I'll merge it in.

Other than that though we have been working on a new version of the subgraph for the exchange contracts, and will most likely have that up within the next week to two weeks. If you want, might be best to hold off on merging this in and we can add these changes to that new subgraph if we don't hear back from zippo in the meantime.

**Comment by benesjan** [comment]
Sure, adding the changes to the new subgraph is totally fine. :blush:

BTW do you know if there is a subgraph which indexes the yield rewards from staking including the information from which pool the reward originates? I need to match the yield rewards to pool share snapshots in order to properly calculate returns in [croco.finance](croco.finance). If it doesn't exist I will probably create such subgraph. Thank you

**Comment by jiro-ono** [comment]
Checkout our [Master Chef Subgraph](https://thegraph.com/explorer/subgraph/sushiswap/master-chef). @matthewlilley just recently added a lot of new stuff for keeping track of the staking pools and their sushi emissions. I haven't had a chance to fully jump into everything that's been added, but I think the `Pool`, `PoolHistory` and `User` entities will have what you are looking for.

Also if you think there is additional stuff we could add to this subgraph or any of the others, definitely let us know and we can work on getting it integrated.

**Comment by benesjan** [comment]
Hello, thank you for letting me know. I had a discussion with @matthewlilley and it was super helpful. I used his code as an inspiration and I have now deployed 2 fully functional subgraphs which contains everything I need. To name them, they are:
1) a subgraph with modifications from this pull request - deployed [here](https://thegraph.com/explorer/subgraph/benesjan/sushi-swap,
2) a subgraph which tracks staked SLPs in the MasterChef contract and all the corresponding rewards individually (a necessity when you want to do proper analysis of user's positions) - [deployment](https://thegraph.com/explorer/subgraph/benesjan/dex-rewards-subgraph), [code](https://github.com/croco-finance/dex-rewards-subgraph).

I would be happy if my subgraphs were of use by other people in the sushi community so feel free to mention them somewhere in the documentation :relieved:.

**Comment by jiro-ono** [comment]
@benesjan Added you guys to the bottom of the ReadMe under a `Community Subgraphs` section.

Gonna go ahead and close this PR out. But if there are any changes you ever wanna make / new features you wanna add to these subgraphs please don't hesitate to add a PR. Love the work you guys are doing btw 😄

**Pull request closed without merging**
